### ISSUE TITLE
Exception if properties file missing

### ISSUE THREAD

**Issue by gkowalski** [xlate/property-inject#3]
I have an example working in my web application, but as I am sending this to customers , they may not have my properties file yet ( or forget to install it ) so I don't want the application server to crash.  Here's the simple class : 

`
 @ManagedBean(name = "adminProperties", eager=true)
 @ApplicationScoped
 public class adminProperties implements Serializable{

    public static String SECURITY_NONE = "None";
    public static String SECURITY_LOW = "Low";
    public static String SECURITY_MED = "Medium";
    public static String SECURITY_HIGH = "High";

    @Inject
    @Property( resource = @PropertyResource("classpath:lattice-admin.properties"), defaultValue = "Medium" )
    private String securityLevel;

    public String getSecurityLevel() {
        return securityLevel;
    }

    public void setSecurityLevel(String securityLevel) {
        this.securityLevel = securityLevel;
    }
    
    
}`

When I run it in my web app without the properties file it crashes the app 
 `
Caused by: java.lang.RuntimeException: javax.enterprise.inject.InjectionException: javax.enterprise.inject.InjectionException: Class-path resource not found: lattice-admin.properties
	at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:292)
	at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:5394)
	at com.sun.enterprise.web.WebModule.contextListenerStart(WebModule.java:743)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:5963)
	... 26 more
Caused by: javax.enterprise.inject.InjectionException: javax.enterprise.inject.InjectionException: Class-path resource not found: lattice-admin.properties
	at io.xlate.inject.PropertyProducerBean.produceProperty(PropertyProducerBean.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:78)
	at org.jboss.weld.injection.producer.ProducerMethodProducer.produce(ProducerMethodProducer.java:95)
	at org.jboss.weld.injection.producer.AbstractMemberProducer.produce(AbstractMemberProducer.java:167)
	at org.jboss.weld.bean.AbstractProducerBean.create(AbstractProducerBean.java:183)
	at org.jboss.weld.context.unbound.DependentContextImpl.get(DependentContextImpl.java:69)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:101)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:761)
	at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:861)
	at org.jboss.weld.injection.FieldInjectionPoint.inject(FieldInjectionPoint.java:92)
	at org.jboss.weld.util.Beans.injectBoundFields(Beans.java:375)
	at org.jboss.weld.util.Beans.injectFieldsAndInitializers(Beans.java:386)
	at org.jboss.weld.injection.producer.ResourceInjector$1.proceed(ResourceInjector.java:70)
	at org.glassfish.weld.services.InjectionServicesImpl.aroundInject(InjectionServicesImpl.java:172)
	at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:46)
	at org.jboss.weld.injection.producer.ResourceInjector.inject(ResourceInjector.java:72)
	at org.jboss.weld.injection.producer.BasicInjectionTarget.inject(BasicInjectionTarget.java:121)
	at org.glassfish.weld.services.JCDIServiceImpl.injectManagedObject(JCDIServiceImpl.java:285)
	at org.glassfish.faces.integration.GlassFishInjectionProvider.inject(GlassFishInjectionProvider.java:189)
	at com.sun.faces.mgbean.BeanBuilder.injectResources(BeanBuilder.java:203)
	at com.sun.faces.mgbean.BeanBuilder.build(BeanBuilder.java:101)
	at com.sun.faces.mgbean.BeanManager.createAndPush(BeanManager.java:409)
	at com.sun.faces.mgbean.BeanManager.create(BeanManager.java:269)
	at com.sun.faces.mgbean.BeanManager.create(BeanManager.java:256)
	at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:259)
	... 29 more
Caused by: javax.enterprise.inject.InjectionException: Class-path resource not found: lattice-admin.properties
	at io.xlate.inject.ClasspathURLStreamHandler.openConnection(ClasspathURLStreamHandler.java:24)
	at java.net.URL.openConnection(URL.java:979)
	at java.net.URL.openStream(URL.java:1045)
	at io.xlate.inject.PropertyFactory.getProperties(PropertyFactory.java:150)
	at io.xlate.inject.PropertyFactory.getProperty(PropertyFactory.java:134)
	at io.xlate.inject.PropertyProducerBean.getProperty(PropertyProducerBean.java:263)
	at io.xlate.inject.PropertyProducerBean.produceProperty(PropertyProducerBean.java:52)
	... 59 more

`

I assumed that I would get the default value ...

**Comment by gkowalski** [comment]
BTW , Works fine when the properties is put into the application Server's classpath.

**Comment by MikeEdgar** [comment]
@gkowalski - thank you for reporting this. I am looking into the issue. This might require a property on the `@PropertyResource` annotation to indicate that a missing resource can be ignored and the default used. Would that be workable for you?

**Comment by MikeEdgar** [comment]
@gkowalski , the new version has been pushed to Maven Central and should be available shortly.

```xml
<dependency>
	<groupId>io.xlate</groupId>
	<artifactId>property-inject</artifactId>
	<version>1.0.5</version>
</dependency>
```
Please update your annotations to use `allowMissingResource` with a value of `true`. You'll also need to add the `value` key for the name of the properties since there are multiple attributes on `@PropertyResource`.

```java
@Inject
@Property(resource = @PropertyResource(value = "classpath:lattice-admin.properties",
                                       allowMissingResource = true),
          defaultValue = "Medium" )
private String securityLevel;
```

**Comment by MikeEdgar** [comment]
Closing issue fixed by adding `allowMissingResource` property. Please open a new issue if another problem arises.
